### ISSUE TITLE
GSOC2016 - Idea #3: Implements SASL mechanisms

### ISSUE THREAD

**Issue by lrascao** [lizenn/erlang-dbus#15]
Hi @jeanparpaillon 
Just to get an understanding of what would this entail, is the idea to implement all the SASL mechanisms  (https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer#SASL_mechanisms)?

**Comment by jeanparpaillon** [comment]
I suppose the title sould be refined as, while D-Bus specifications tells every SASL mechanism should be supported, they are not all implemented by *reference implementation* (C one) and non-SASL authentication mechanism are implemented (nonce-TCP transport...).

In order to be fully compatible with D-Bus existing implementations, it would be preferable to:
1. identify all required mechanisms (SASL and non-SASL)
2. identify all required transports (I suppose transport and authentication mechanisms are not 100% decoupled)
3. Check which combination should be prioritized and doable in a GSoC.

I consider solving 1 and 2 is a prerequisite for being a good candidate for 3 ;)

**Comment by lrascao** [comment]
Ah, i see, i thought the ideas were separate projects that could be picked independently. I find the whole project interesting but i have doubts on wether i could allocate enough time for it, what would be your estimate of the workload for the whole thing?

**Comment by jeanparpaillon** [comment]
I don't have a precise idea of the workload as I have not yet identified what mechanisms are *really* required.

That's why I propose, as a first step, to identify these mechanisms (which shouldn't take more than a half day...) then discuss which ones are feasible as GSoC.

**Comment by lrascao** [comment]
Got it, closing issue, hopefully will open a new one with a better analysis

**Comment by jeanparpaillon** [comment]
Great, thanks !
